version: '2'

services:
    fhem:
        restart: always
        ports:
            - "8083:8083"
            - "7072:7072"
        image: fhem/fhem:latest
        volumes:
            - ./fhem/core/:/opt/fhem/
        networks:
            - fhem-network
        environment:
            FHEM_UID: 1000
            FHEM_GID: 1000
            TIMEOUT: 10
            RESTART: 1
            TELNETPORT: 7072
            TZ: Europe/Berlin
        depends_on:
            - "mysql"
            - "mqtt"

#    habridge:
#        restart: always
#        #build: habridge
#        image: habridge/ha-bridge-raspberrypi3
#        network_mode: host
#        volumes:
#            - ./habridge/data/:/opt/habridge/data/

    mysql:
        restart: always
        expose:
            - "3306"
            - "33060"
        ports:
            - "3306:3306"
            - "33060:33060"
        image: linuxserver/mariadb
        volumes:
            - ./mysql/config:/config
            - ./mysql/data:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        networks:
            - fhem-network

    mqtt:
        restart: always
        expose:
            - "1883"
            - "9001"
        ports:
            - "1883:1883"
            - "9001:9001"
        image: eclipse-mosquitto
        networks:
            - fhem-network
        volumes:
            - ./mqtt/config/:/mosquitto/config/
            - ./mqtt/log/:/mosquitto/log/
            - ./mqtt/data/:/mosquitto/data/
       
              #    nodered:
              #        restart: always
              #        expose:
              #            - "1880"
              #        ports:
              #            - "1880:1880"
              #        image: nodered/node-red-docker:0.20.7
              #        user: "1000:1000"
              #        volumes:
              #            - ./nodered/data/:/data/
              #        networks:
              #            - fhem-network
              #        depends_on:
              #            - "mqtt"

    hmcfgusb:
        restart: always
        build: hmcfgusb
        privileged: true
        volumes:
            - /dev/bus/usb:/dev/bus/usb
        networks:
            - fhem-network

networks:
    fhem-network:
        driver: bridge
